In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
%matplotlib inline

In [301]:
df_lung = pd.read_csv('/home/davidhenslovitz/Galvanize/ZNAHealth/CSV/RESPIR.csv', converters={'State-county recode': lambda x: str(x), 'CS Schema v0204+': lambda x: str(x)})

/home/davidhenslovitz/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (7,24,25,54,86) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [302]:
df_lung = df_lung.replace(r'\s+', np.nan, regex=True)

In [303]:
df_lung = df_lung[df_lung['CS Schema v0204+']=='063']

In [304]:
df_lung.shape

(608048, 132)

In [305]:
# df_lung["state"] = df_lung["State-county recode"].str[0:2]
# df_lung["county"] = df_lung["State-county recode"].str[2:5]

In [306]:
df_lung = df_lung[['Race/Ethnicity','Sex','Age at diagnosis', 'Year of diagnosis', 'Year of Birth','CS Schema v0204+','Race recode (White, Black, Other)','Race recode (W, B, AI, API)','Origin recode NHIA (Hispanic, Non-Hisp)','State-county recode']]

In [307]:
df_lung.head()

,Race/Ethnicity,Sex,Age at diagnosis,Year of diagnosis,Year of Birth,CS Schema v0204+,"Race recode (White, Black, Other)","Race recode (W, B, AI, API)","Origin recode NHIA (Hispanic, Non-Hisp)",State-county recode
0,1,1,81,1995,1914,063,1,1,0,09009
1,1,1,88,1973,1884,063,1,1,0,09009
2,1,1,76,1978,1902,063,1,1,0,09009
3,1,2,64,1975,1910,063,1,1,0,09001
4,1,2,66,1991,1924,063,1,1,0,09009

In [308]:
df_lung.loc[ df_lung['Age at diagnosis'].apply(pd.to_numeric) <= 30, 'Age'] = '0'
df_lung.loc[(df_lung['Age at diagnosis'].apply(pd.to_numeric) > 30) & (df_lung['Age at diagnosis'].apply(pd.to_numeric) <= 60), 'Age'] = '1'
df_lung.loc[ df_lung['Age at diagnosis'].apply(pd.to_numeric) > 60, 'Age'] = '2'
df_lung.loc[df_lung['Race recode (White, Black, Other)'].apply(pd.to_numeric)>3,'Race recode (White, Black, Other)']=3
df_lung.shape

(608048, 11)

In [309]:
#df_lung['Age at diagnosis'] = df_lung['Age at diagnosis'].astype(int)
df_grouped = df_lung.groupby(['State-county recode', 'Race recode (White, Black, Other)','Sex','Year of diagnosis']).size().reset_index(name='Count')
#df_grouped.loc[df_grouped['Race recode (White, Black, Other)'].apply(pd.to_numeric)>3,'Race recode (White, Black, Other)']='3'

df_grouped[df_grouped['Race recode (White, Black, Other)']==3]
#df_grouped.head(50)
#pd.DataFrame(df_grouped).reset_index().head()
# df_grouped.pivot(index=df_grouped.index.get_level_values('State-county recode'), columns='Year of diagnosis', values='Count')

,State-county recode,"Race recode (White, Black, Other)",Sex,Year of diagnosis,Count
168,06001,3,1,1973,6
169,06001,3,1,1974,11
170,06001,3,1,1975,10
171,06001,3,1,1976,16
172,06001,3,1,1977,12
173,06001,3,1,1978,12
174,06001,3,1,1979,23
175,06001,3,1,1980,17
176,06001,3,1,1981,12
177,06001,3,1,1982,23
178,06001,3,1,1983,22
179,06001,3,1,1984,19
180,06001,3,1,1985,30
181,06001,3,1,1986,29
182,06001,3,1,1987,25
183,06001,3,1,1988,35
184,06001,3,1,1989,35
185,06001,3,1,1990,31
186,06001,3,1,1991,26
187,06001,3,1,1992,39
188,06001,3,1,1993,54
189,06001,3,1,1994,42
190,06001,3,1,1995,38
191,06001,3,1,1996,46
192,06001,3,1,1997,43
193,06001,3,1,1998,48
194,06001,3,1,1999,56
195,06001,3,1,2000,73
196,06001,3,1,2001,67
197,06001,3,1,2002,69
...,...,...,...,...,...
20955,53073,3,1,2006,1
20956,53073,3,1,2007,4
20957,53073,3,1,2008,3
20958,53073,3,1,2009,1
20959,53073,3,1,2010,2
20960,53073,3,1,2012,3
20961,53073,3,1,2013,7
20962,53073,3,1,2014,2
20963,53073,3,2,1974,1
20964,53073,3,2,1985,1
20965,53073,3,2,1986,1
20966,53073,3,2,1987,1
20967,53073,3,2,1988,1
20968,53073,3,2,1996,1
20969,53073,3,2,1998,1
20970,53073,3,2,1999,1
20971,53073,3,2,2000,1
20972,53073,3,2,2001,2
20973,53073,3,2,2003,3
20974,53073,3,2,2004,3
20975,53073,3,2,2005,2
20976,53073,3,2,2006,5
20977,53073,3,2,2007,1
20978,53073,3,2,2008,3
20979,53073,3,2,2009,1
20980,53073,3,2,2010,9
20981,53073,3,2,2011,6
20982,53073,3,2,2012,3
20983,53073,3,2,2013,4
20984,53073,3,2,2014,5

In [310]:
df_grouped['Combined'] = df_grouped['State-county recode'].astype(str)+df_grouped['Race recode (White, Black, Other)'].astype(str)+df_grouped.Sex.astype(str)
df_grouped = df_grouped.pivot(index='Combined',columns='Year of diagnosis',values='Count').reset_index()
df_grouped.head(20)

Year of diagnosis,Combined,1973,1974,1975,1976,1977,1978,1979,1980,1981,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,0600111,298.0,320.0,287.0,305.0,324.0,318.0,313.0,374.0,343.0,...,202.0,178.0,212.0,204.0,212.0,184.0,194.0,179.0,176.0,163.0
1,0600112,109.0,128.0,153.0,128.0,169.0,171.0,182.0,197.0,193.0,...,227.0,211.0,215.0,214.0,229.0,211.0,201.0,179.0,215.0,208.0
2,0600121,50.0,58.0,62.0,68.0,90.0,104.0,78.0,94.0,102.0,...,75.0,72.0,75.0,69.0,72.0,61.0,64.0,83.0,53.0,64.0
3,0600122,12.0,24.0,24.0,34.0,26.0,21.0,28.0,40.0,38.0,...,76.0,73.0,64.0,64.0,83.0,59.0,62.0,73.0,76.0,58.0
4,0600131,6.0,11.0,10.0,16.0,12.0,12.0,23.0,17.0,12.0,...,70.0,74.0,80.0,62.0,88.0,79.0,79.0,85.0,102.0,99.0
5,0600132,4.0,3.0,4.0,7.0,5.0,5.0,6.0,9.0,4.0,...,55.0,70.0,59.0,51.0,85.0,64.0,66.0,66.0,63.0,78.0
6,0601311,170.0,202.0,180.0,181.0,213.0,194.0,215.0,201.0,220.0,...,205.0,195.0,220.0,199.0,206.0,205.0,195.0,198.0,216.0,160.0
7,0601312,67.0,61.0,78.0,97.0,117.0,95.0,105.0,122.0,134.0,...,223.0,243.0,250.0,223.0,217.0,216.0,272.0,243.0,225.0,220.0
8,0601321,14.0,13.0,14.0,19.0,13.0,19.0,14.0,19.0,27.0,...,29.0,21.0,25.0,40.0,27.0,40.0,29.0,36.0,30.0,23.0
9,0601322,4.0,2.0,5.0,5.0,5.0,8.0,7.0,5.0,5.0,...,24.0,28.0,29.0,26.0,24.0,40.0,32.0,32.0,31.0,29.0
10,0601331,NaN,1.0,2.0,3.0,3.0,4.0,2.0,6.0,7.0,...,20.0,36.0,22.0,26.0,18.0,31.0,32.0,34.0,35.0,34.0
11,0601332,2.0,NaN,NaN,1.0,2.0,1.0,1.0,1.0,5.0,...,22.0,25.0,27.0,20.0,17.0,16.0,23.0,24.0,32.0,31.0
12,0604111,47.0,59.0,56.0,63.0,83.0,90.0,74.0,62.0,57.0,...,57.0,56.0,67.0,69.0,65.0,55.0,61.0,66.0,56.0,60.0
13,0604112,32.0,28.0,43.0,55.0,31.0,44.0,58.0,34.0,52.0,...,73.0,74.0,74.0,71.0,71.0,88.0,76.0,71.0,69.0,82.0
14,0604121,NaN,3.0,NaN,2.0,1.0,1.0,NaN,2.0,3.0,...,1.0,3.0,3.0,2.0,5.0,3.0,1.0,2.0,2.0,3.0
15,0604122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,2.0,3.0
16,0604131,1.0,NaN,1.0,NaN,NaN,1.0,NaN,3.0,NaN,...,NaN,1.0,2.0,4.0,1.0,5.0,1.0,6.0,2.0,3.0
17,0604132,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,1.0,2.0,3.0,5.0,1.0,5.0,3.0,3.0,3.0,1.0
18,0607511,278.0,291.0,260.0,251.0,262.0,255.0,230.0,261.0,241.0,...,134.0,129.0,127.0,110.0,109.0,127.0,97.0,116.0,93.0,106.0
19,0607512,102.0,132.0,135.0,141.0,122.0,132.0,139.0,143.0,132.0,...,96.0,116.0,108.0,89.0,107.0,117.0,86.0,94.0,99.0,82.0

In [311]:
df_grouped.shape

(873, 43)

In [312]:
df_grouped.drop([1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999], axis=1,inplace=True)

In [313]:
df_grouped.head(20)

Year of diagnosis,Combined,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,0600111,290.0,242.0,223.0,214.0,215.0,202.0,178.0,212.0,204.0,212.0,184.0,194.0,179.0,176.0,163.0
1,0600112,233.0,222.0,232.0,262.0,224.0,227.0,211.0,215.0,214.0,229.0,211.0,201.0,179.0,215.0,208.0
2,0600121,92.0,75.0,96.0,79.0,61.0,75.0,72.0,75.0,69.0,72.0,61.0,64.0,83.0,53.0,64.0
3,0600122,76.0,60.0,91.0,73.0,73.0,76.0,73.0,64.0,64.0,83.0,59.0,62.0,73.0,76.0,58.0
4,0600131,73.0,67.0,69.0,83.0,76.0,70.0,74.0,80.0,62.0,88.0,79.0,79.0,85.0,102.0,99.0
5,0600132,45.0,44.0,45.0,45.0,36.0,55.0,70.0,59.0,51.0,85.0,64.0,66.0,66.0,63.0,78.0
6,0601311,197.0,216.0,206.0,220.0,180.0,205.0,195.0,220.0,199.0,206.0,205.0,195.0,198.0,216.0,160.0
7,0601312,237.0,261.0,230.0,251.0,223.0,223.0,243.0,250.0,223.0,217.0,216.0,272.0,243.0,225.0,220.0
8,0601321,22.0,27.0,21.0,40.0,28.0,29.0,21.0,25.0,40.0,27.0,40.0,29.0,36.0,30.0,23.0
9,0601322,21.0,24.0,28.0,32.0,29.0,24.0,28.0,29.0,26.0,24.0,40.0,32.0,32.0,31.0,29.0
10,0601331,28.0,32.0,22.0,21.0,34.0,20.0,36.0,22.0,26.0,18.0,31.0,32.0,34.0,35.0,34.0
11,0601332,14.0,25.0,17.0,23.0,24.0,22.0,25.0,27.0,20.0,17.0,16.0,23.0,24.0,32.0,31.0
12,0604111,58.0,56.0,72.0,71.0,57.0,57.0,56.0,67.0,69.0,65.0,55.0,61.0,66.0,56.0,60.0
13,0604112,58.0,75.0,84.0,70.0,67.0,73.0,74.0,74.0,71.0,71.0,88.0,76.0,71.0,69.0,82.0
14,0604121,5.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,5.0,3.0,1.0,2.0,2.0,3.0
15,0604122,2.0,NaN,2.0,2.0,3.0,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,2.0,3.0
16,0604131,2.0,5.0,4.0,1.0,2.0,NaN,1.0,2.0,4.0,1.0,5.0,1.0,6.0,2.0,3.0
17,0604132,1.0,4.0,3.0,2.0,5.0,1.0,2.0,3.0,5.0,1.0,5.0,3.0,3.0,3.0,1.0
18,0607511,138.0,151.0,126.0,113.0,132.0,134.0,129.0,127.0,110.0,109.0,127.0,97.0,116.0,93.0,106.0
19,0607512,118.0,112.0,138.0,116.0,104.0,96.0,116.0,108.0,89.0,107.0,117.0,86.0,94.0,99.0,82.0

In [314]:
#df_grouped['Age']=df_grouped.Combined.str[:1]
df_grouped['State-county recode']=df_grouped.Combined.str[:5]
df_grouped['Race recode (White, Black, Other)']=df_grouped.Combined.str[5:6]
df_grouped['Sex']=df_grouped.Combined.str[6:]

#df_grouped.loc[df_grouped['Race recode (White, Black, Other)'].apply(pd.to_numeric)>3,'Race recode (White, Black, Other)']=3

#df_grouped.groupby('State-county recode')[2010,2011,2012,2013,2014].sum()
df_grouped.head(20)

Year of diagnosis,Combined,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,State-county recode,"Race recode (White, Black, Other)",Sex
0,0600111,290.0,242.0,223.0,214.0,215.0,202.0,178.0,212.0,204.0,212.0,184.0,194.0,179.0,176.0,163.0,06001,1,1
1,0600112,233.0,222.0,232.0,262.0,224.0,227.0,211.0,215.0,214.0,229.0,211.0,201.0,179.0,215.0,208.0,06001,1,2
2,0600121,92.0,75.0,96.0,79.0,61.0,75.0,72.0,75.0,69.0,72.0,61.0,64.0,83.0,53.0,64.0,06001,2,1
3,0600122,76.0,60.0,91.0,73.0,73.0,76.0,73.0,64.0,64.0,83.0,59.0,62.0,73.0,76.0,58.0,06001,2,2
4,0600131,73.0,67.0,69.0,83.0,76.0,70.0,74.0,80.0,62.0,88.0,79.0,79.0,85.0,102.0,99.0,06001,3,1
5,0600132,45.0,44.0,45.0,45.0,36.0,55.0,70.0,59.0,51.0,85.0,64.0,66.0,66.0,63.0,78.0,06001,3,2
6,0601311,197.0,216.0,206.0,220.0,180.0,205.0,195.0,220.0,199.0,206.0,205.0,195.0,198.0,216.0,160.0,06013,1,1
7,0601312,237.0,261.0,230.0,251.0,223.0,223.0,243.0,250.0,223.0,217.0,216.0,272.0,243.0,225.0,220.0,06013,1,2
8,0601321,22.0,27.0,21.0,40.0,28.0,29.0,21.0,25.0,40.0,27.0,40.0,29.0,36.0,30.0,23.0,06013,2,1
9,0601322,21.0,24.0,28.0,32.0,29.0,24.0,28.0,29.0,26.0,24.0,40.0,32.0,32.0,31.0,29.0,06013,2,2
10,0601331,28.0,32.0,22.0,21.0,34.0,20.0,36.0,22.0,26.0,18.0,31.0,32.0,34.0,35.0,34.0,06013,3,1
11,0601332,14.0,25.0,17.0,23.0,24.0,22.0,25.0,27.0,20.0,17.0,16.0,23.0,24.0,32.0,31.0,06013,3,2
12,0604111,58.0,56.0,72.0,71.0,57.0,57.0,56.0,67.0,69.0,65.0,55.0,61.0,66.0,56.0,60.0,06041,1,1
13,0604112,58.0,75.0,84.0,70.0,67.0,73.0,74.0,74.0,71.0,71.0,88.0,76.0,71.0,69.0,82.0,06041,1,2
14,0604121,5.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,5.0,3.0,1.0,2.0,2.0,3.0,06041,2,1
15,0604122,2.0,NaN,2.0,2.0,3.0,NaN,2.0,NaN,NaN,2.0,1.0,1.0,NaN,2.0,3.0,06041,2,2
16,0604131,2.0,5.0,4.0,1.0,2.0,NaN,1.0,2.0,4.0,1.0,5.0,1.0,6.0,2.0,3.0,06041,3,1
17,0604132,1.0,4.0,3.0,2.0,5.0,1.0,2.0,3.0,5.0,1.0,5.0,3.0,3.0,3.0,1.0,06041,3,2
18,0607511,138.0,151.0,126.0,113.0,132.0,134.0,129.0,127.0,110.0,109.0,127.0,97.0,116.0,93.0,106.0,06075,1,1
19,0607512,118.0,112.0,138.0,116.0,104.0,96.0,116.0,108.0,89.0,107.0,117.0,86.0,94.0,99.0,82.0,06075,1,2

In [315]:
df_grouped.fillna(0,inplace=True)
df_grouped.head()

Year of diagnosis,Combined,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,State-county recode,"Race recode (White, Black, Other)",Sex
0,0600111,290.0,242.0,223.0,214.0,215.0,202.0,178.0,212.0,204.0,212.0,184.0,194.0,179.0,176.0,163.0,06001,1,1
1,0600112,233.0,222.0,232.0,262.0,224.0,227.0,211.0,215.0,214.0,229.0,211.0,201.0,179.0,215.0,208.0,06001,1,2
2,0600121,92.0,75.0,96.0,79.0,61.0,75.0,72.0,75.0,69.0,72.0,61.0,64.0,83.0,53.0,64.0,06001,2,1
3,0600122,76.0,60.0,91.0,73.0,73.0,76.0,73.0,64.0,64.0,83.0,59.0,62.0,73.0,76.0,58.0,06001,2,2
4,0600131,73.0,67.0,69.0,83.0,76.0,70.0,74.0,80.0,62.0,88.0,79.0,79.0,85.0,102.0,99.0,06001,3,1

In [291]:
df_grouped.shape

(1927, 19)

In [57]:
#df_grouped.pivot(index=df_grouped.index.get_level_values(0), columns=df_grouped.index.get_level_values(1), values='Count')
df_grouped.pivot(index='State-county recode', columns='Year of diagnosis', values='Count').shape

(209, 42)

In [316]:
population = pd.read_table('/home/davidhenslovitz/Galvanize/ZNAHealth/SEER_1973_2014_TEXTDATA/populations/white_black_other/yr1973_2014.seer9/singleages.txt',header=None)

In [317]:
population1 = population[:1422890]
population2 = population[1422890:]

In [318]:
indices = [(0,4),(4,6),(6,8),(8,11),(11,13),(13,14),(14,15),(15,16),(16,18),(18,28)]
dct={}
for num in range(len(population1)):
    string = ""
    x = population1.iloc[num][0]
    for i in range(len(indices)):
        string += x[indices[i][0]:indices[i][1]] + ", "
    dct[num] = string[:-2]

In [319]:
indices = [(0,4),(4,6),(6,8),(8,11),(11,13),(13,14),(14,15),(15,16),(16,18),(18,28)]
dct2={}
for num in range(len(population2)):
    string = ""
    x = population2.iloc[num][0]
    for i in range(len(indices)):
        string += x[indices[i][0]:indices[i][1]] + ", "
    dct2[num] = string[:-2]

In [320]:
clean_df = pd.DataFrame(columns=['Year','State postal abbr','State FIPS','County FIPS','Registry','Race','Origin','Sex','Age','Population'])

In [321]:
for i, k in enumerate(dct.values()):
    dct[i] = k.split(', ')

In [322]:
for i, k in enumerate(dct2.values()):
    dct2[i] = k.split(', ')

In [323]:
df1 = pd.DataFrame.from_dict(dct, orient='index')
df2 = pd.DataFrame.from_dict(dct2, orient='index')
df_new = pd.concat([df1, df2])
df_new.head()

      0   1   2    3   4  5  6  7   8           9
0  1973  CA  06  001  01  1  9  1  00  00005529.0
1  1973  CA  06  001  01  1  9  1  01  00005638.0
2  1973  CA  06  001  01  1  9  1  02  00006070.0
3  1973  CA  06  001  01  1  9  1  03  00005993.0
4  1973  CA  06  001  01  1  9  1  04  00005876.0

In [324]:
df_new.columns = clean_df.columns
df_new['State-county recode']=df_new['State FIPS']+df_new['County FIPS']
df_new.Population = df_new.Population.apply(pd.to_numeric)

In [325]:
df_new.loc[ df_new.Age.apply(pd.to_numeric) <= 30, 'Age'] = 0
df_new.loc[(df_new.Age.apply(pd.to_numeric) > 30) & (df_new.Age.apply(pd.to_numeric) <= 60), 'Age'] = 1
df_new.loc[ df_new.Age.apply(pd.to_numeric) > 60, 'Age'] = 2

In [326]:
pop_binned = pd.DataFrame(df_new.groupby(['State-county recode','Race','Sex','Year'])['Population'].sum().reset_index())

In [327]:
#pop_binned.pivot(pop_binned.index,'Year', 'Population')
pop_binned.head()

  State-county recode Race Sex  Year  Population
0               06001    1   1  1973    416937.0
1               06001    1   1  1974    414072.0
2               06001    1   1  1975    409054.0
3               06001    1   1  1976    407865.0
4               06001    1   1  1977    403651.0

In [328]:
#pop_binned['Combined'] = pop_binned.Age.astype(str)+pop_binned['State-county recode'].astype(str)+pop_binned.Race.astype(str)+pop_binned.Sex.astype(str)
pop_binned['Combined'] = pop_binned['State-county recode'].astype(str)+pop_binned.Race.astype(str)+pop_binned.Sex.astype(str)
pop_binned.Year = pop_binned.Year.astype(int)
pop_final = pop_binned.pivot(index='Combined',columns='Year',values='Population').reset_index()

In [329]:
#pop_final['Age']=pop_final.Combined.str[:1]
pop_final['State-county recode']=pop_final.Combined.str[:5]
pop_final['Race']=pop_final.Combined.str[5:6]
pop_final['Sex']=pop_final.Combined.str[6:]

In [330]:
pop_final.drop([1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999], axis=1,inplace=True)
#pop_final.drop(['1973','1974'],axis=1)

In [331]:
pop_final[pop_final['State-county recode']=='06001']

Year,Combined,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,State-county recode,Race,Sex
0,0600111,436899.0,438510.0,431849.0,425037.0,418563.0,413911.0,411279.0,411723.0,414505.0,416940.0,417746.0,420948.0,425236.0,430410.0,435883.0,06001,1,1
1,0600112,435721.0,435837.0,429229.0,423076.0,417045.0,412694.0,410372.0,410128.0,413139.0,416165.0,416509.0,419752.0,424591.0,429442.0,435087.0,06001,1,2
2,0600121,108456.0,107549.0,104959.0,102891.0,101111.0,99282.0,98714.0,98521.0,99138.0,100199.0,100482.0,100495.0,100391.0,100079.0,100135.0,06001,2,1
3,0600122,124576.0,122862.0,120063.0,117843.0,115609.0,113459.0,112599.0,112100.0,112156.0,113192.0,113303.0,113141.0,112963.0,112401.0,111721.0,06001,2,2
4,0600131,167215.0,177626.0,182665.0,186705.0,190279.0,194185.0,198338.0,203922.0,210899.0,217567.0,223921.0,229964.0,237042.0,245597.0,254322.0,06001,3,1
5,0600132,176973.0,187100.0,193341.0,198611.0,203114.0,208014.0,213182.0,219321.0,227371.0,234476.0,241793.0,248752.0,256729.0,265916.0,275702.0,06001,3,2

In [340]:
combined = pd.merge(df_grouped,pop_final,how='inner',on='Combined')

In [341]:
for i in range(2000,2015):
    combined[i] = combined[str(i)+"_x"]/combined[str(i)+"_y"]
    #combined.drop(str(i)+"_x",inplace=True)

In [342]:
#combined = combined[['Combined',2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014]]

In [343]:
combined.head()

,Combined,2000_x,2001_x,2002_x,2003_x,2004_x,2005_x,2006_x,2007_x,2008_x,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,0600111,290.0,242.0,223.0,214.0,215.0,202.0,178.0,212.0,204.0,...,0.000488,0.000433,0.000515,0.000492,0.000508,0.000440,0.000461,0.000421,0.000409,0.000374
1,0600112,233.0,222.0,232.0,262.0,224.0,227.0,211.0,215.0,214.0,...,0.000550,0.000514,0.000524,0.000518,0.000550,0.000507,0.000479,0.000422,0.000501,0.000478
2,0600121,92.0,75.0,96.0,79.0,61.0,75.0,72.0,75.0,69.0,...,0.000755,0.000729,0.000761,0.000696,0.000719,0.000607,0.000637,0.000827,0.000530,0.000639
3,0600122,76.0,60.0,91.0,73.0,73.0,76.0,73.0,64.0,64.0,...,0.000670,0.000648,0.000571,0.000571,0.000733,0.000521,0.000548,0.000646,0.000676,0.000519
4,0600131,73.0,67.0,69.0,83.0,76.0,70.0,74.0,80.0,62.0,...,0.000360,0.000373,0.000392,0.000294,0.000404,0.000353,0.000344,0.000359,0.000415,0.000389

In [356]:
combined.groupby('State-county recode_x')['Combined',2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014].sum()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
State-county recode_x,,,,,,,,,,,,,,,
06001,0.003348,0.002859,0.003340,0.003181,0.002862,0.003088,0.003026,0.003033,0.002795,0.003278,0.002692,0.002733,0.002931,0.002768,0.002682
06013,0.002736,0.003169,0.002703,0.003307,0.002980,0.002725,0.002881,0.002877,0.002910,0.002451,0.003050,0.002868,0.002928,0.002835,0.002452
06041,0.003062,0.002883,0.003362,0.002896,0.003537,0.001479,0.002741,0.002379,0.002572,0.002961,0.003091,0.002050,0.002461,0.002495,0.003016
06075,0.004565,0.004162,0.004254,0.004717,0.004190,0.004883,0.004635,0.004250,0.004268,0.004599,0.004276,0.003958,0.004542,0.003935,0.004252
06081,0.003674,0.003761,0.002868,0.003154,0.004106,0.003545,0.003330,0.003953,0.003210,0.003681,0.002964,0.003141,0.003169,0.003180,0.002478
09001,0.002515,0.002407,0.002598,0.002686,0.002417,0.002302,0.002702,0.002769,0.002586,0.002425,0.002827,0.002523,0.002543,0.002820,0.002484
09003,0.002606,0.002884,0.003161,0.002856,0.002894,0.002915,0.002843,0.003104,0.003089,0.003088,0.002835,0.003051,0.002818,0.003158,0.002712
09005,0.003708,0.002437,0.001744,0.003561,0.002434,0.003420,0.002538,0.002900,0.002192,0.002107,0.002246,0.004732,0.003690,0.003429,0.003960
09007,0.003106,0.002474,0.002402,0.002319,0.002834,0.004324,0.003693,0.002703,0.003358,0.003321,0.005785,0.003138,0.003852,0.003785,0.002715
09009,0.002780,0.002931,0.003092,0.002929,0.002900,0.002744,0.003469,0.003587,0.003337,0.003172,0.003123,0.003349,0.003577,0.003622,0.003267
09011,0.003054,0.003793,0.003180,0.003100,0.002363,0.002879,0.003130,0.003057,0.003067,0.003232,0.004137,0.003150,0.003152,0.003405,0.002789
09013,0.001212,0.001918,0.001764,0.002848,0.001668,0.002599,0.001315,0.001167,0.001898,0.001620,0.001320,0.002163,0.002732,0.002522,0.001418
09015,0.001614,0.002766,0.002161,0.002129,0.002616,0.002162,0.001878,0.003121,0.001473,0.002327,0.002225,0.001271,0.002816,0.001785,0.002451
13063,0.002279,0.002277,0.002135,0.002929,0.002622,0.002367,0.002846,0.002793,0.003192,0.002961,0.003182,0.002514,0.003214,0.002786,0.003750
13067,0.001896,0.001464,0.001848,0.001505,0.001528,0.001623,0.002123,0.001828,0.001648,0.001866,0.001585,0.002049,0.002046,0.002187,0.002256
13089,0.002435,0.002197,0.001823,0.002330,0.002368,0.002232,0.002266,0.002348,0.002279,0.002289,0.002252,0.002355,0.002364,0.002337,0.002062
13121,0.002441,0.002315,0.002373,0.002381,0.002212,0.002000,0.002135,0.002337,0.002451,0.002400,0.002234,0.001882,0.002175,0.002246,0.002379
13135,0.001258,0.001625,0.001406,0.001450,0.001507,0.001454,0.001445,0.001403,0.001479,0.001678,0.001408,0.001688,0.001696,0.001576,0.001959
15001,0.002716,0.002812,0.002545,0.002941,0.002799,0.004727,0.002628,0.003371,0.002657,0.003038,0.003528,0.003640,0.002620,0.002578,0.002085
15003,0.002843,0.002340,0.002659,0.002540,0.002835,0.002802,0.003208,0.002972,0.002754,0.002696,0.002615,0.002719,0.002506,0.002994,0.002588
15005,0.000000,0.000000,0.000000,0.046512,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15007,0.012074,0.002053,0.001958,0.001905,0.003274,0.002862,0.002130,0.002551,0.002231,0.010152,0.002205,0.002198,0.002254,0.002058,0.002004
15009,0.002206,0.001827,0.003386,0.004095,0.001975,0.003162,0.002174,0.003106,0.002192,0.002107,0.001857,0.002109,0.002453,0.003209,0.002590
19001,0.001698,0.000988,0.001774,0.003270,0.001751,0.002278,0.003317,0.001525,0.002602,0.001052,0.001843,0.002665,0.001891,0.003015,0.002211
19003,0.000882,0.001852,0.002785,0.003244,0.002827,0.001925,0.001928,0.000967,0.001940,0.002496,0.001507,0.003037,0.001566,0.002098,0.001576
19005,0.001923,0.001827,0.000992,0.002247,0.000562,0.002259,0.001833,0.001984,0.001004,0.001716,0.001285,0.001009,0.001589,0.000731,0.001902
19007,0.031652,0.000998,0.002331,0.001796,0.001830,0.002277,0.002775,0.001570,0.003150,0.002543,0.003174,0.001753,0.002262,0.002741,0.002414
19009,0.000900,0.001859,0.002431,0.001523,0.001577,0.002901,0.003247,0.002599,0.001645,0.002018,0.002648,0.001712,0.000691,0.000335,0.002105
19011,0.025583,0.001657,0.001093,0.001709,0.001313,0.001692,0.001160,0.001320,0.001551,0.001859,0.001243,0.002171,0.001964,0.001497,0.001661
19013,0.002715,0.002615,0.002464,0.002846,0.002919,0.002484,0.002960,0.004913,0.003952,0.003096,0.004074,0.005365,0.003033,0.003176,0.003572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49025,0.001020,0.000335,0.000331,0.000670,0.001327,0.000969,0.001532,0.000609,0.002099,0.000882,0.000867,0.001130,0.002295,0.000000,0.000571
49027,0.000162,0.000847,0.000327,0.000490,0.000342,0.000859,0.000504,0.000346,0.000166,0.000496,0.000331,0.000820,0.000671,0.000667,0.000506
49029,0.000000,0.000548,0.000000,0.000262,0.000265,0.000000,0.000244,0.000000,0.000666,0.000219,0.000422,0.000209,0.000000,0.000398,0.000000
49031,0.000000,0.001370,0.001504,0.005776,0.005435,0.001383,0.000000,0.002924,0.002703,0.000000,0.000000,0.002706,0.002681,0.001307,0.001410
49033,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001801,0.072295,0.000846,0.000912,0.001733,0.000000
49035,0.000671,0.000629,0.001029,0.001287,0.001145,0.001322,0.001325,0.001130,0.000936,0.000731,0.001173,0.001260,0.000976,0.001060,0.001392
49037,0.001223,0.001322,0.001247,0.001541,0.001530,0.000898,0.000312,0.000290,0.000845,0.001389,0.000000,0.001094,0.000276,0.000259,0.000524
49039,0.000537,0.001053,0.000613,0.000426,0.000680,0.000588,0.000979,0.000157,0.000075,0.000387,0.000456,0.000536,0.000967,0.000652,0.000363
49041,0.004895,0.000434,0.000646,0.004475,0.000847,0.000952,0.000725,0.001018,0.000690,0.000890,0.000789,0.000495,0.000789,0.000701,0.000698
49043,0.000262,0.004351,0.000317,0.000374,0.000360,0.000236,0.000120,0.000118,0.003476,0.000348,0.000164,0.000444,0.000274,0.000375,0.000315
49045,0.000807,0.000434,0.000418,0.000535,0.000434,0.000381,0.000525,0.004948,0.000482,0.003301,0.003763,0.000700,0.000591,0.000376,0.000509
49047,0.000708,0.001681,0.001453,0.000927,0.001155,0.001218,0.001806,0.001881,0.001500,0.000332,0.000622,0.001192,0.000194,0.000688,0.000952
49049,0.000430,0.000380,0.000272,0.000215,0.000535,0.000326,0.000213,0.000191,0.000599,0.000228,0.000411,0.000334,0.000431,0.000202,0.000240
49051,0.000388,0.000625,0.000476,0.000116,0.000220,0.000637,0.000301,0.000285,0.000272,0.006308,0.000427,0.000419,0.004123,0.000159,0.000370
49053,0.000747,0.001538,0.000525,0.000599,0.001294,0.001329,0.001332,0.000774,0.002557,0.001202,0.001218,0.002851,0.001944,0.001147,0.002465
49055,0.001594,0.000791,0.000000,0.000000,0.001616,0.000820,0.001553,0.000000,0.000000,0.001463,0.000000,0.001489,0.000000,0.000764,0.000000
49057,0.000498,0.001089,0.002228,0.001905,0.001154,0.001476,0.002128,0.001881,0.002325,0.001443,0.001781,0.002104,0.002064,0.001483,0.001442
53009,0.003116,0.002910,0.004267,0.002930,0.004909,0.002533,0.003691,0.003392,0.003451,0.010668,0.007784,0.005049,0.003124,0.003731,0.009919
53027,0.004439,0.003300,0.004721,0.003418,0.003433,0.008427,0.007215,0.002710,0.004228,0.004040,0.003729,0.003722,0.003383,0.003444,0.002948
53029,0.002362,0.002588,0.001981,0.005384,0.002510,0.002679,0.003469,0.002383,0.001943,0.002903,0.003149,0.002068,0.001671,0.003277,0.002756
53031,0.001677,0.002442,0.002182,0.004471,0.001821,0.002608,0.002180,0.004404,0.005228,0.002224,0.002640,0.002365,0.006435,0.003620,0.004082
53033,0.002882,0.002841,0.002846,0.002441,0.002810,0.002673,0.002810,0.002772,0.002658,0.002694,0.002681,0.002411,0.002555,0.002307,0.002402
53035,0.003070,0.002790,0.003039,0.002729,0.003488,0.001951,0.002599,0.002436,0.002462,0.002481,0.002625,0.002402,0.002851,0.003541,0.003065
53045,0.003220,0.005594,0.006434,0.003453,0.003392,0.003657,0.004937,0.004449,0.009320,0.004379,0.003054,0.004462,0.003125,0.002299,0.002839
53053,0.002880,0.002954,0.003034,0.003131,0.003064,0.003243,0.003031,0.002751,0.003263,0.003387,0.003614,0.003756,0.003211,0.003072,0.003670
53055,0.002053,0.001707,0.000693,0.001253,0.001216,0.001740,0.001088,0.000802,0.001191,0.001321,0.001049,0.001579,0.001306,0.001681,0.001183
53057,0.005794,0.004317,0.002862,0.001794,0.003550,0.003276,0.003603,0.005132,0.002115,0.002155,0.002789,0.001700,0.003368,0.003631,0.002788
53061,0.001815,0.002123,0.001968,0.002489,0.001817,0.002181,0.002391,0.002278,0.001862,0.002618,0.002347,0.002655,0.002361,0.002239,0.002437
53067,0.003071,0.002530,0.002513,0.003548,0.002900,0.003447,0.001987,0.003290,0.002935,0.002487,0.002381,0.002450,0.002163,0.002175,0.002568
53073,0.002744,0.003131,0.001422,0.003074,0.002697,0.001655,0.003901,0.001926,0.002063,0.001670,0.002688,0.002145,0.002530,0.003668,0.002047